# Generated by Django 5.2.10 on 2026-01-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('program_year_section', models.CharField(max_length=200)),
                ('rfid_uid', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.CharField(blank=True, choices=[('Borrowing', 'Borrowing'), ('Reading', 'Reading'), ('Facility', 'Facility')], max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.student')),
            ],
        ),
    ]
