# Generated by Django 5.2.10 on 2026-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='program',
            field=models.CharField(blank=True, choices=[('BSMA', 'BSMA'), ('BSCPE', 'BSCPE'), ('BTVTED', 'BTVTED'), ('BSE', 'BSE'), ('BPA', 'BPA')], max_length=10, null=True),
        ),
    ]
