# Generated by Django 5.2.10 on 2026-01-22 15:49

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_attendancelog_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program_year_section',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BSMA', 'BSMA'), ('BSCPE', 'BSCPE'), ('BTVTED', 'BTVTED'), ('BSE', 'BSE'), ('BPA', 'BPA')], default='BSCPE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
