# Generated by Django on automated edit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_remove_student_program_year_section_student_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
