# Generated by Django 5.2.10 on 2026-01-25 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0002_book_year_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
