# Generated by Django 5.2.10 on 2026-01-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0004_rfiduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidlog',
            name='uid',
        ),
        migrations.AddField(
            model_name='rfidlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='elibrary.rfiduser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfidlog',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
