# Generated by Django 5.2.10 on 2026-01-25 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0005_remove_rfidlog_uid_rfidlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidlog',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rfidlog',
            name='scanned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
