# Generated by Django 5.2.10 on 2026-01-30 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0006_rfidlog_consumed_alter_rfidlog_scanned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('thesis', 'Thesis')], max_length=10)),
                ('activity_type', models.CharField(choices=[('recorded', 'Recorded'), ('saved', 'Saved')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elibrary.book')),
                ('thesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elibrary.thesis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_activities', to='elibrary.rfiduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
