# Generated by Django 5.2.10 on 2026-01-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0008_libraryaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLibraryActivity',
        ),
    ]
