# Generated by Django 6.0.1 on 2026-01-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_level',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
            preserve_default=False,
        ),
    ]
