# Generated by Django 5.2.10 on 2026-03-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0009_delete_userlibraryactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
