# Generated by Django 5.2.10 on 2026-01-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0007_userlibraryactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('thesis', 'Thesis')], max_length=10)),
                ('content_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('recorded', 'Recorded'), ('saved', 'Saved')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_actions', to='elibrary.rfiduser')),
            ],
        ),
    ]
